{
 "title": "ML Service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "model", "query": "lr,cb" },
   { "name": "gender", "query": "f,m" }
  ]
 },
 "panels": [
  { "title": "Health Bar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(stats.ml_service.predict_gender.$model.count, '1min'), -2)"
    }
   ]
  },
  {
   "title": "Feature Extraction",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.timers.ml_service.predict_gender.cb.timing.feature_extraction.mean_90, 1000)"
    }
   ]
  },
  {
   "title": "Feature Extraction (thr 1)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.timers.ml_service.predict_gender.cb.timing.feature_extraction.mean_90, 1000)"
    }
   ]
  },
  { "title": "Requests Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Model request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(stats.ml_service.predict_gender.$model.count, '1min'), -2)"
    }
   ]
  },
  {
   "title": "Catboost / LogReg ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "alias(divideSeries(stats.ml_service.predict_gender.cb.count, stats.ml_service.predict_gender.lr.count), 'cb/lr')"
    }
   ]
  },
  { "title": "Prediction Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Avg predictions per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "aliasByTags(movingAverage(stats.ml_service.predict_gender.$model.result.$gender.count, '1min'), -2, -4)"
    }
   ]
  },
  {
   "title": "Output Probas (avg per 5 min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "groupByNodes(movingAverage(stats.gauges.ml_service.predict_gender.$model.result.$gender.proba, '5min'), 'last', -2, -4)"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Feature Extraction Timing (median)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByTags(stats.timers.ml_service.predict_gender.$model.timing.feature_extraction.median, -4, -1)"
    }
   ]
  },
  {
   "title": "Feature Extraction Timing (mean)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByTags(stats.timers.ml_service.predict_gender.$model.timing.feature_extraction.mean, -4, -1)"
    }
   ]
  },
  {
   "title": "Feature Extraction Timing (std)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByTags(stats.timers.ml_service.predict_gender.$model.timing.feature_extraction.std, -4, -1)"
    }
   ]
  }
 ]
}